name: Client CI/CD

on:
  push:
    branches:
      - client
    paths:
      - 'Client/**'
      
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Client
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
          
      - name: Download flutter libs
        run: flutter pub get
        working-directory: Client/rum_logger_client
        
      - name: Build flutter web app
        run: flutter build web
        working-directory: Client/rum_logger_client 
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_DUNE_0E5DF5703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/Client/rum_logger_client" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build/web" # Built app content directory - optional
